// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Filters for the public artworks list</summary>
public class ArtworkListQuery
{
    [JsonPropertyName("pageNumber")]
    public int? PageNumber { get; set; }

    [JsonPropertyName("pageSize")]
    public int? PageSize { get; set; }

    [JsonPropertyName("artistName")]
    public string? ArtistName { get; set; }

    [JsonPropertyName("categoryName")]
    public string? CategoryName { get; set; }

    [JsonPropertyName("tagName")]
    public string? TagName { get; set; }

    [JsonPropertyName("status")]
    public string? Status { get; set; }

    public ArtworkListQuery() { }

    public ArtworkListQuery(int? pageNumber, int? pageSize, string? artistName, string? categoryName, string? tagName, string? status)
    {
        PageNumber = pageNumber;
        PageSize = pageSize;
        ArtistName = artistName;
        CategoryName = categoryName;
        TagName = tagName;
        Status = status;
    }
}
