// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Detailed artwork payload</summary>
public class ArtworkDetail
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("artistName")]
    public string ArtistName { get; set; }

    [JsonPropertyName("artistId")]
    public Guid ArtistId { get; set; }

    [JsonPropertyName("initialPrice")]
    public double InitialPrice { get; set; }

    [JsonPropertyName("buyNowPrice")]
    public double? BuyNowPrice { get; set; }

    [JsonPropertyName("currentBid")]
    public double CurrentBid { get; set; }

    [JsonPropertyName("auctionStartTime")]
    public DateTime AuctionStartTime { get; set; }

    [JsonPropertyName("auctionEndTime")]
    public DateTime AuctionEndTime { get; set; }

    [JsonPropertyName("status")]
    public string Status { get; set; }

    [JsonPropertyName("categoryName")]
    public string CategoryName { get; set; }

    [JsonPropertyName("tags")]
    public List<string> Tags { get; set; }

    [JsonPropertyName("totalBids")]
    public int TotalBids { get; set; }

    [JsonPropertyName("imageUrl")]
    public string ImageUrl { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    public ArtworkDetail() { }

    public ArtworkDetail(Guid id, string title, string description, string artistName, Guid artistId, double initialPrice, double? buyNowPrice, double currentBid, DateTime auctionStartTime, DateTime auctionEndTime, string status, string categoryName, List<string> tags, int totalBids, string imageUrl, DateTime createdAt)
    {
        Id = id;
        Title = title;
        Description = description;
        ArtistName = artistName;
        ArtistId = artistId;
        InitialPrice = initialPrice;
        BuyNowPrice = buyNowPrice;
        CurrentBid = currentBid;
        AuctionStartTime = auctionStartTime;
        AuctionEndTime = auctionEndTime;
        Status = status;
        CategoryName = categoryName;
        Tags = tags;
        TotalBids = totalBids;
        ImageUrl = imageUrl;
        CreatedAt = createdAt;
    }
}
