// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Lightweight artwork card</summary>
public class Artwork
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("artistName")]
    public string ArtistName { get; set; }

    [JsonPropertyName("initialPrice")]
    public double InitialPrice { get; set; }

    [JsonPropertyName("currentBid")]
    public double CurrentBid { get; set; }

    [JsonPropertyName("auctionEndTime")]
    public DateTime AuctionEndTime { get; set; }

    [JsonPropertyName("status")]
    public string Status { get; set; }

    [JsonPropertyName("imageUrl")]
    public string ImageUrl { get; set; }

    public Artwork() { }

    public Artwork(Guid id, string title, string artistName, double initialPrice, double currentBid, DateTime auctionEndTime, string status, string imageUrl)
    {
        Id = id;
        Title = title;
        ArtistName = artistName;
        InitialPrice = initialPrice;
        CurrentBid = currentBid;
        AuctionEndTime = auctionEndTime;
        Status = status;
        ImageUrl = imageUrl;
    }
}
