// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Paged list response for artworks</summary>
public class PagedArtwork
{
    [JsonPropertyName("items")]
    public List<Artwork> Items { get; set; }

    [JsonPropertyName("totalCount")]
    public int TotalCount { get; set; }

    [JsonPropertyName("pageNumber")]
    public int PageNumber { get; set; }

    [JsonPropertyName("pageSize")]
    public int PageSize { get; set; }

    [JsonPropertyName("totalPages")]
    public int TotalPages { get; set; }

    [JsonPropertyName("hasNextPage")]
    public bool HasNextPage { get; set; }

    [JsonPropertyName("hasPreviousPage")]
    public bool HasPreviousPage { get; set; }

    public PagedArtwork() { }

    public PagedArtwork(List<Artwork> items, int totalCount, int pageNumber, int pageSize, int totalPages, bool hasNextPage, bool hasPreviousPage)
    {
        Items = items;
        TotalCount = totalCount;
        PageNumber = pageNumber;
        PageSize = pageSize;
        TotalPages = totalPages;
        HasNextPage = hasNextPage;
        HasPreviousPage = hasPreviousPage;
    }
}
