// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Basic pagination query</summary>
public class PaginationQuery
{
    [JsonPropertyName("pageNumber")]
    public int? PageNumber { get; set; }

    [JsonPropertyName("pageSize")]
    public int? PageSize { get; set; }

    public PaginationQuery() { }

    public PaginationQuery(int? pageNumber, int? pageSize)
    {
        PageNumber = pageNumber;
        PageSize = pageSize;
    }
}
