// AUTO-GENERATED BY VELD — DO NOT EDIT
using System;

namespace VeldGenerated.Errors;

/// <summary>Typed API exception with a machine-readable code and HTTP status.</summary>
public class ApiException : Exception
{
    public string Code { get; }
    public int Status { get; }
    public string Timestamp { get; }

    public ApiException(string code, int status, string message) : base(message)
    {
        Code = code;
        Status = status;
        Timestamp = DateTime.UtcNow.ToString("o");
    }

    public bool IsErrorCode(string errorCode) => Code == errorCode;
    public bool IsHttpStatus(int httpStatus) => Status == httpStatus;
    public ApiErrorResponse ToErrorResponse() => new(Message, Code, Status);

    public static bool IsApiException(Exception ex) => ex is ApiException;
    public static ApiErrorResponse ToErrorResponse(Exception ex) =>
        ex is ApiException ae ? ae.ToErrorResponse() : new(ex.Message, "INTERNAL_ERROR", 500);
}
