// AUTO-GENERATED BY VELD — DO NOT EDIT
namespace VeldGenerated.Errors;

/// <summary>500 Internal Server Error — throw from service implementations for quick status responses.</summary>
public class InternalException : ApiException
{
    public InternalException(string? message = null, string? code = null)
        : base(code ?? "INTERNAL_SERVER_ERROR", 500, message ?? "Internal Server Error") { }
}
