// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Data for new account registration</summary>
public class RegisterInput
{
    [JsonPropertyName("email")]
    public string Email { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("password")]
    public string Password { get; set; }

    [JsonPropertyName("role")]
    public string? Role { get; set; }

    public RegisterInput() { }

    public RegisterInput(string email, string name, string password, string? role)
    {
        Email = email;
        Name = name;
        Password = password;
        Role = role;
    }
}
