// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Common query parameters for list endpoints</summary>
public class ListQuery
{
    [JsonPropertyName("search")]
    public string? Search { get; set; }

    [JsonPropertyName("limit")]
    public int? Limit { get; set; }

    [JsonPropertyName("offset")]
    public int? Offset { get; set; }

    public ListQuery() { }

    public ListQuery(string? search, int? limit, int? offset)
    {
        Search = search;
        Limit = limit;
        Offset = offset;
    }
}
