// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>A platform user</summary>
public class User
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonPropertyName("email")]
    public string Email { get; set; }

    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("bio")]
    public string? Bio { get; set; }

    [JsonPropertyName("role")]
    public UserRole Role { get; set; }

    [JsonPropertyName("verified")]
    public bool Verified { get; set; } = false;

    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    public User() { }

    public User(Guid id, string email, string name, string? bio, UserRole role, bool verified, DateTime createdAt)
    {
        Id = id;
        Email = email;
        Name = name;
        Bio = bio;
        Role = role;
        Verified = verified;
        CreatedAt = createdAt;
    }
}
