// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { adminApi } from '../client/adminApi';
import { VeldApiError } from '../client/_internal';
import type { PendingArtist, AdminActionMessage, PendingArtwork } from '../types';

export const getPendingArtistsKey = ['Admin', 'getPendingArtists'] as const;
/** Get all artists waiting for approval */
export function useGetPendingArtists(options?: Omit<UseQueryOptions<PendingArtist[], VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Admin', 'getPendingArtists'],
    queryFn: () => adminApi.getPendingArtists(),
    ...options,
  });
}

/** Approve an artist account */
export function useApproveArtist(options?: Omit<UseMutationOptions<AdminActionMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => adminApi.approveArtist(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Admin'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Reject an artist account */
export function useRejectArtist(options?: Omit<UseMutationOptions<AdminActionMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => adminApi.rejectArtist(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Admin'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const getPendingArtworksKey = ['Admin', 'getPendingArtworks'] as const;
/** Get all artworks waiting for approval */
export function useGetPendingArtworks(options?: Omit<UseQueryOptions<PendingArtwork[], VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Admin', 'getPendingArtworks'],
    queryFn: () => adminApi.getPendingArtworks(),
    ...options,
  });
}

/** Approve an artwork */
export function useApproveArtwork(options?: Omit<UseMutationOptions<AdminActionMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => adminApi.approveArtwork(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Admin'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Reject an artwork */
export function useRejectArtwork(options?: Omit<UseMutationOptions<AdminActionMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => adminApi.rejectArtwork(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Admin'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const adminQueryKeys = {
  getPendingArtists: getPendingArtistsKey,
  getPendingArtworks: getPendingArtworksKey,
} as const;

export const adminHooks = {
  useGetPendingArtists,
  useApproveArtist,
  useRejectArtist,
  useGetPendingArtworks,
  useApproveArtwork,
  useRejectArtwork,
};
