// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { artworksApi } from '../client/artworksApi';
import { VeldApiError } from '../client/_internal';
import type { PagedArtwork, ArtworkListQuery, ArtworkDetail, PaginationQuery, CreateArtworkInput, Artwork, AdminActionMessage, ExtendAuctionTimeInput } from '../types';

export const getArtworksKey = (query?: ArtworkListQuery) => ['Artworks', 'getArtworks', query] as const;
/** Get artworks with optional filtering and pagination */
export function useGetArtworks(query?: ArtworkListQuery, options?: Omit<UseQueryOptions<PagedArtwork, VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Artworks', 'getArtworks', query],
    queryFn: () => artworksApi.getArtworks(query),
    ...options,
  });
}

export const getArtworkByIdKey = (id: string) => ['Artworks', 'getArtworkById', id] as const;
/** Get detailed information for one artwork */
export function useGetArtworkById(id: string, options?: Omit<UseQueryOptions<ArtworkDetail, VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Artworks', 'getArtworkById', id],
    queryFn: () => artworksApi.getArtworkById(id),
    ...options,
  });
}

export const getArtworksByArtistKey = (artistId: string, query?: PaginationQuery) => ['Artworks', 'getArtworksByArtist', artistId, query] as const;
/** Get paged artworks for one artist */
export function useGetArtworksByArtist(artistId: string, query?: PaginationQuery, options?: Omit<UseQueryOptions<PagedArtwork, VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Artworks', 'getArtworksByArtist', artistId, query],
    queryFn: () => artworksApi.getArtworksByArtist(artistId, query),
    ...options,
  });
}

/** Create a new artwork (Artist role) */
export function useCreateArtwork(options?: Omit<UseMutationOptions<Artwork, VeldApiError, { input: CreateArtworkInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: CreateArtworkInput }) => artworksApi.createArtwork(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Artworks'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Update an owned artwork (Artist role) */
export function useUpdateArtwork(options?: Omit<UseMutationOptions<Artwork, VeldApiError, { id: string; input: CreateArtworkInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string; input: CreateArtworkInput }) => artworksApi.updateArtwork(vars.id, vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Artworks'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Delete an owned artwork (Artist role) */
export function useDeleteArtwork(options?: Omit<UseMutationOptions<AdminActionMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => artworksApi.deleteArtwork(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Artworks'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Extend auction end time (Artist role) */
export function useExtendAuctionTime(options?: Omit<UseMutationOptions<Artwork, VeldApiError, { id: string; input: ExtendAuctionTimeInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string; input: ExtendAuctionTimeInput }) => artworksApi.extendAuctionTime(vars.id, vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Artworks'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const artworksQueryKeys = {
  getArtworks: getArtworksKey,
  getArtworkById: getArtworkByIdKey,
  getArtworksByArtist: getArtworksByArtistKey,
} as const;

export const artworksHooks = {
  useGetArtworks,
  useGetArtworkById,
  useGetArtworksByArtist,
  useCreateArtwork,
  useUpdateArtwork,
  useDeleteArtwork,
  useExtendAuctionTime,
};
