// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { authApi } from '../client/authApi';
import { VeldApiError } from '../client/_internal';
import type { LoginInput, AuthToken, RegisterInput, RegisterArtistInput, User, SuccessMessage, UserRole } from '../types';

/** Log in with credentials */
export function useLogin(options?: Omit<UseMutationOptions<AuthToken, VeldApiError, { input: LoginInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: LoginInput }) => authApi.login(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Auth'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Register a new account */
export function useRegister(options?: Omit<UseMutationOptions<AuthToken, VeldApiError, { input: RegisterInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: RegisterInput }) => authApi.register(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Auth'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Register a new artist account (pending approval) */
export function useRegisterArtist(options?: Omit<UseMutationOptions<AuthToken, VeldApiError, { input: RegisterArtistInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: RegisterArtistInput }) => authApi.registerArtist(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Auth'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const getMeKey = ['Auth', 'getMe'] as const;
/** Get the currently authenticated user */
export function useGetMe(options?: Omit<UseQueryOptions<User, VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Auth', 'getMe'],
    queryFn: () => authApi.getMe(),
    ...options,
  });
}

/** Log out and invalidate session */
export function useLogout(options?: Omit<UseMutationOptions<SuccessMessage, VeldApiError, void>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => authApi.logout(),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Auth'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const authQueryKeys = {
  getMe: getMeKey,
} as const;

export const authHooks = {
  useLogin,
  useRegister,
  useRegisterArtist,
  useGetMe,
  useLogout,
};
