// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { bidApi } from '../client/bidApi';
import { VeldApiError } from '../client/_internal';
import type { Bid } from '../types';

/**  */
export function useCreateBid(options?: Omit<UseMutationOptions<string, VeldApiError, { input: Bid }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: Bid }) => bidApi.createBid(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['bid'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const getBidsKey = (id: string) => ['bid', 'getBids', id] as const;
/**  */
export function useGetBids(id: string, options?: Omit<UseQueryOptions<Bid[], VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['bid', 'getBids', id],
    queryFn: () => bidApi.getBids(id),
    ...options,
  });
}

export const bidQueryKeys = {
  getBids: getBidsKey,
} as const;

export const bidHooks = {
  useCreateBid,
  useGetBids,
};
