// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { categoriesApi } from '../client/categoriesApi';
import { VeldApiError } from '../client/_internal';
import type { Category, CreateCategoryInput } from '../types';

export const listCategoriesKey = ['Categories', 'listCategories'] as const;
/** List all categories */
export function useListCategories(options?: Omit<UseQueryOptions<Category[], VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Categories', 'listCategories'],
    queryFn: () => categoriesApi.listCategories(),
    ...options,
  });
}

/** Create category by name */
export function useCreateCategory(options?: Omit<UseMutationOptions<Category, VeldApiError, { input: CreateCategoryInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: CreateCategoryInput }) => categoriesApi.createCategory(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Categories'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const categoriesQueryKeys = {
  listCategories: listCategoriesKey,
} as const;

export const categoriesHooks = {
  useListCategories,
  useCreateCategory,
};
