// AUTO-GENERATED BY VELD — DO NOT EDIT
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import type { UseQueryOptions, UseMutationOptions } from '@tanstack/react-query';
import { usersApi } from '../client/usersApi';
import { VeldApiError } from '../client/_internal';
import type { User, ListQuery, CreateUserInput, UpdateUserInput, SuccessMessage, UserRole } from '../types';

export const listUsersKey = (query?: ListQuery) => ['Users', 'listUsers', query] as const;
/** List all users with optional filters */
export function useListUsers(query?: ListQuery, options?: Omit<UseQueryOptions<User[], VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Users', 'listUsers', query],
    queryFn: () => usersApi.listUsers(query),
    ...options,
  });
}

export const getUserKey = (id: string) => ['Users', 'getUser', id] as const;
/** Get a single user by ID */
export function useGetUser(id: string, options?: Omit<UseQueryOptions<User, VeldApiError>, 'queryKey' | 'queryFn'>) {
  return useQuery({
    queryKey: ['Users', 'getUser', id],
    queryFn: () => usersApi.getUser(id),
    ...options,
  });
}

/** Create a new user */
export function useCreateUser(options?: Omit<UseMutationOptions<User, VeldApiError, { input: CreateUserInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { input: CreateUserInput }) => usersApi.createUser(vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Users'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Update an existing user */
export function useUpdateUser(options?: Omit<UseMutationOptions<User, VeldApiError, { id: string; input: UpdateUserInput }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string; input: UpdateUserInput }) => usersApi.updateUser(vars.id, vars.input),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Users'] });
      options?.onSuccess?.(...args);
    },
  });
}

/** Delete a user */
export function useDeleteUser(options?: Omit<UseMutationOptions<SuccessMessage, VeldApiError, { id: string }>, 'mutationFn'>) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (vars: { id: string }) => usersApi.deleteUser(vars.id),
    ...options,
    onSuccess: (...args) => {
      queryClient.invalidateQueries({ queryKey: ['Users'] });
      options?.onSuccess?.(...args);
    },
  });
}

export const usersQueryKeys = {
  listUsers: listUsersKey,
  getUser: getUserKey,
} as const;

export const usersHooks = {
  useListUsers,
  useGetUser,
  useCreateUser,
  useUpdateUser,
  useDeleteUser,
};
