// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Message returned after approve/reject actions</summary>
public class AdminActionMessage
{
    [JsonPropertyName("message")]
    public string Message { get; set; }

    public AdminActionMessage() { }

    public AdminActionMessage(string message)
    {
        Message = message;
    }
}
