// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Artwork waiting for admin approval</summary>
public class PendingArtwork
{
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    [JsonPropertyName("title")]
    public string Title { get; set; }

    [JsonPropertyName("description")]
    public string Description { get; set; }

    [JsonPropertyName("initialPrice")]
    public double InitialPrice { get; set; }

    [JsonPropertyName("artistName")]
    public string ArtistName { get; set; }

    [JsonPropertyName("createdAt")]
    public DateTime CreatedAt { get; set; }

    public PendingArtwork() { }

    public PendingArtwork(Guid id, string title, string description, double initialPrice, string artistName, DateTime createdAt)
    {
        Id = id;
        Title = title;
        Description = description;
        InitialPrice = initialPrice;
        ArtistName = artistName;
        CreatedAt = createdAt;
    }
}
