// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Error response payload</summary>
public class ErrorMessage
{
    [JsonPropertyName("error")]
    public string Error { get; set; }

    public ErrorMessage() { }

    public ErrorMessage(string error)
    {
        Error = error;
    }
}
