// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Http;

namespace VeldGenerated.Middleware;

/// <summary>
/// Middleware interface for the Admin module.
/// Implement this interface and register it with dependency injection.
/// </summary>
public interface IAdminMiddleware
{
    /// <summary>RequireAdmin middleware — return true to proceed, false to reject.</summary>
    Task<bool> RequireAdminAsync(HttpContext context);

}
