// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Http;

namespace VeldGenerated.Middleware;

/// <summary>
/// Middleware interface for the Artworks module.
/// Implement this interface and register it with dependency injection.
/// </summary>
public interface IArtworksMiddleware
{
    /// <summary>RequireArtist middleware — return true to proceed, false to reject.</summary>
    Task<bool> RequireArtistAsync(HttpContext context);

}
