// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Http;

namespace VeldGenerated.Middleware;

/// <summary>
/// Middleware interface for the Auth module.
/// Implement this interface and register it with dependency injection.
/// </summary>
public interface IAuthMiddleware
{
    /// <summary>RateLimit middleware — return true to proceed, false to reject.</summary>
    Task<bool> RateLimitAsync(HttpContext context);

    /// <summary>RequireAuth middleware — return true to proceed, false to reject.</summary>
    Task<bool> RequireAuthAsync(HttpContext context);

}
