// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;

namespace VeldGenerated.Controllers;

/// <summary>Admin review and approval endpoints</summary>
[ApiController]
[Route("api/admin")]
public class AdminController : ControllerBase
{
    private readonly IAdminService _service;

    public AdminController(IAdminService service)
    {
        _service = service;
    }

    /// <summary>Get all artists waiting for approval</summary>
    [HttpGet("artists/pending")]
    public async Task<IActionResult> GetPendingArtists()
    {
        try
        {
            var result = await _service.GetPendingArtists();
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Approve an artist account</summary>
    [HttpPut("artists/{id}/approve")]
    public async Task<IActionResult> ApproveArtist([FromRoute] string Id)
    {
        try
        {
            var result = await _service.ApproveArtist(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Reject an artist account</summary>
    [HttpPut("artists/{id}/reject")]
    public async Task<IActionResult> RejectArtist([FromRoute] string Id)
    {
        try
        {
            var result = await _service.RejectArtist(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Get all artworks waiting for approval</summary>
    [HttpGet("artworks/pending")]
    public async Task<IActionResult> GetPendingArtworks()
    {
        try
        {
            var result = await _service.GetPendingArtworks();
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Approve an artwork</summary>
    [HttpPut("artworks/{id}/approve")]
    public async Task<IActionResult> ApproveArtwork([FromRoute] string Id)
    {
        try
        {
            var result = await _service.ApproveArtwork(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Reject an artwork</summary>
    [HttpPut("artworks/{id}/reject")]
    public async Task<IActionResult> RejectArtwork([FromRoute] string Id)
    {
        try
        {
            var result = await _service.RejectArtwork(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }
}
