// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ArtAuction.Domain.Authorization;
using System.Collections.Generic;
using MediatR;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;
using ArtAuction.Application.Features.Admin.Commands.CreateCategory;
using ArtAuction.Application.Features.Admin.Commands.CreateTag;
using ArtAuction.Application.Features.Admin.Queries.GetAllCategories;
using ArtAuction.Application.Features.Admin.Queries.GetAllTags;

namespace VeldGenerated.Controllers;

/// <summary>Admin review and approval endpoints</summary>
[ApiController]
[Route("api/admin")]
public class AdminController : ControllerBase
{
    private readonly IAdminService _service;
    private readonly ISender _sender;

    public AdminController(IAdminService service, ISender sender)
    {
        _service = service;
        _sender = sender;
    }

    /// <summary>Get all artists waiting for approval</summary>
    [HttpGet("artists/pending")]
    [Authorize(Policy = Permissions.ManageArtistAccounts)]
    public async Task<IActionResult> GetPendingArtists()
    {
        try
        {
            var result = await _service.GetPendingArtists();
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Approve an artist account</summary>
    [HttpPut("artists/{id}/approve")]
    [Authorize(Policy = Permissions.ManageArtistAccounts)]
    public async Task<IActionResult> ApproveArtist([FromRoute] string Id)
    {
        try
        {
            var result = await _service.ApproveArtist(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Reject an artist account</summary>
    [HttpPut("artists/{id}/reject")]
    [Authorize(Policy = Permissions.ManageArtistAccounts)]
    public async Task<IActionResult> RejectArtist([FromRoute] string Id)
    {
        try
        {
            var result = await _service.RejectArtist(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Get all artworks waiting for approval</summary>
    [HttpGet("artworks/pending")]
    [Authorize(Policy = Permissions.ReviewArtworks)]
    public async Task<IActionResult> GetPendingArtworks()
    {
        try
        {
            var result = await _service.GetPendingArtworks();
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Approve an artwork</summary>
    [HttpPut("artworks/{id}/approve")]
    [Authorize(Policy = Permissions.ReviewArtworks)]
    public async Task<IActionResult> ApproveArtwork([FromRoute] string Id)
    {
        try
        {
            var result = await _service.ApproveArtwork(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Reject an artwork</summary>
    [HttpPut("artworks/{id}/reject")]
    [Authorize(Policy = Permissions.ReviewArtworks)]
    public async Task<IActionResult> RejectArtwork([FromRoute] string Id)
    {
        try
        {
            var result = await _service.RejectArtwork(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    // ─── CATEGORY ENDPOINTS ───────────────────────────────────────────────────

    /// <summary>
    /// POST /api/admin/categories
    /// Creates a new category that artists can use when posting artworks.
    /// </summary>
    [HttpPost("categories")]
    [Authorize(Policy = Permissions.CatalogManage)]
    public async Task<IActionResult> CreateCategory([FromBody] CreateCategoryCommand command)
    {
        try
        {
            var result = await _sender.Send(command);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return Conflict(new { message = ex.Message });
        }
    }

    /// <summary>
    /// GET /api/admin/categories
    /// Returns all available categories.
    /// Artists use this to pick a category when creating an artwork.
    /// Buyers use this to filter artworks.
    /// </summary>
    [HttpGet("categories")]
    [Authorize(Policy = Permissions.CatalogManage)]
    public async Task<IActionResult> GetAllCategories()
    {
        var result = await _sender.Send(new GetAllCategoriesQuery());
        return Ok(result);
    }

    // ─── TAG ENDPOINTS ────────────────────────────────────────────────────────

    /// <summary>
    /// POST /api/admin/tags
    /// Creates a new tag that artists can use when posting artworks.
    /// </summary>
    [HttpPost("tags")]
    [Authorize(Policy = Permissions.CatalogManage)]
    public async Task<IActionResult> CreateTag([FromBody] CreateTagCommand command)
    {
        try
        {
            var result = await _sender.Send(command);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return Conflict(new { message = ex.Message });
        }
    }

    /// <summary>
    /// GET /api/admin/tags
    /// Returns all available tags.
    /// Artists use this to pick tags when creating an artwork.
    /// Buyers use this to filter artworks.
    /// </summary>
    [HttpGet("tags")]
    [Authorize(Policy = Permissions.CatalogManage)]
    public async Task<IActionResult> GetAllTags()
    {
        var result = await _sender.Send(new GetAllTagsQuery());
        return Ok(result);
    }
}