// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ArtAuction.Domain.Authorization;
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;

namespace VeldGenerated.Controllers;

/// <summary>Artwork browsing and management</summary>
[ApiController]
[Route("api/artworks")]
[AllowAnonymous]
public class ArtworksController : ControllerBase
{
    private readonly IArtworksService _service;

    public ArtworksController(IArtworksService service)
    {
        _service = service;
    }

    /// <summary>Get artworks with optional filtering and pagination</summary>
    [HttpGet]
    public async Task<IActionResult> GetArtworks([FromQuery] Dictionary<string, string> query)
    {
        try
        {
            var result = await _service.GetArtworks(query);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Get detailed information for one artwork</summary>
    [HttpGet("{id}")]
    public async Task<IActionResult> GetArtworkById([FromRoute] string Id)
    {
        try
        {
            var result = await _service.GetArtworkById(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Get paged artworks for one artist</summary>
    [HttpGet("artist/{artistId}")]
    public async Task<IActionResult> GetArtworksByArtist([FromRoute] string ArtistId, [FromQuery] Dictionary<string, string> query)
    {
        try
        {
            var result = await _service.GetArtworksByArtist(ArtistId, query);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Create a new artwork (Artist role)</summary>
    [HttpPost]
    [Authorize(Roles = "Artist")]
    [Authorize(Policy = Permissions.ArtworksCreate)]
    public async Task<IActionResult> CreateArtwork([FromBody] CreateArtworkInput input)
    {
        try
        {
            var result = await _service.CreateArtwork(input);
            return StatusCode(201, result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Update an owned artwork (Artist role)</summary>
    [HttpPut("{id}")]
    [Authorize(Roles = "Artist")]
    [Authorize(Policy = Permissions.ArtworksUpdate)]
    public async Task<IActionResult> UpdateArtwork([FromRoute] string Id, [FromBody] CreateArtworkInput input)
    {
        try
        {
            var result = await _service.UpdateArtwork(Id, input);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Delete an owned artwork (Artist role)</summary>
    [HttpDelete("{id}")]
    [Authorize(Roles = "Artist")]
    [Authorize(Policy = Permissions.ArtworksDelete)]
    public async Task<IActionResult> DeleteArtwork([FromRoute] string Id)
    {
        try
        {
            var result = await _service.DeleteArtwork(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Extend auction end time (Artist role)</summary>
    [HttpPut("{id}/extend")]
    [Authorize(Roles = "Artist")]
    [Authorize(Policy = Permissions.ArtworksExtendAuction)]
    public async Task<IActionResult> ExtendAuctionTime([FromRoute] string Id, [FromBody] ExtendAuctionTimeInput input)
    {
        try
        {
            var result = await _service.ExtendAuctionTime(Id, input);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }
}
