// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ArtAuction.Domain.Authorization;
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;

namespace VeldGenerated.Controllers;

[ApiController]
[Route("api/bids")]
public class BidController : ControllerBase
{
    private readonly IBidService _service;

    public BidController(IBidService service)
    {
        _service = service;
    }

    [HttpPost]
    [Authorize(Roles = "Buyer")]
    [Authorize(Policy = Permissions.BidsPlace)]
    public async Task<IActionResult> CreateBid([FromBody] Bid input)
    {
        try
        {
            var result = await _service.CreateBid(input);
            return StatusCode(201, result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    [HttpGet("artworks/{id}")]
    [AllowAnonymous]
    public async Task<IActionResult> GetBids([FromRoute] string Id)
    {
        try
        {
            var result = await _service.GetBids(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }
}
