// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;

namespace VeldGenerated.Controllers;

/// <summary>Category management</summary>
[ApiController]
[Route("api/categories")]
public class CategoriesController : ControllerBase
{
    private readonly ICategoriesService _service;

    public CategoriesController(ICategoriesService service)
    {
        _service = service;
    }

    /// <summary>List all categories</summary>
    [HttpGet]
    public async Task<IActionResult> ListCategories()
    {
        try
        {
            var result = await _service.ListCategories();
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Create category by name</summary>
    [HttpPost]
    public async Task<IActionResult> CreateCategory([FromBody] CreateCategoryInput input)
    {
        try
        {
            var result = await _service.CreateCategory(input);
            return StatusCode(201, result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }
}
