// AUTO-GENERATED BY VELD — DO NOT EDIT
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using ArtAuction.Domain.Authorization;
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;
using VeldGenerated.Services;

namespace VeldGenerated.Controllers;

/// <summary>User management</summary>
[ApiController]
[Route("api/users")]
[Authorize(Roles = "Admin")]
[Authorize(Policy = Permissions.UsersView)]
public class UsersController : ControllerBase
{
    private readonly IUsersService _service;

    public UsersController(IUsersService service)
    {
        _service = service;
    }

    /// <summary>List all users with optional filters</summary>
    [HttpGet]
    public async Task<IActionResult> ListUsers([FromQuery] Dictionary<string, string> query)
    {
        try
        {
            var result = await _service.ListUsers(query);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Get a single user by ID</summary>
    [HttpGet("{id}")]
    public async Task<IActionResult> GetUser([FromRoute] string Id)
    {
        try
        {
            var result = await _service.GetUser(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Create a new user</summary>
    [HttpPost]
    public async Task<IActionResult> CreateUser([FromBody] CreateUserInput input)
    {
        try
        {
            var result = await _service.CreateUser(input);
            return StatusCode(201, result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Update an existing user</summary>
    [HttpPut("{id}")]
    public async Task<IActionResult> UpdateUser([FromRoute] string Id, [FromBody] UpdateUserInput input)
    {
        try
        {
            var result = await _service.UpdateUser(Id, input);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }

    /// <summary>Delete a user</summary>
    [HttpDelete("{id}")]
    public async Task<IActionResult> DeleteUser([FromRoute] string Id)
    {
        try
        {
            var result = await _service.DeleteUser(Id);
            return Ok(result);
        }
        catch (Exception e)
        {
            return StatusCode(500, new { error = e.Message });
        }
    }
}
