// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

/// <summary>Payload to create category</summary>
public class CreateCategoryInput
{
    [JsonPropertyName("name")]
    public string Name { get; set; }

    [JsonPropertyName("description")]
    public string? Description { get; set; }

    public CreateCategoryInput() { }

    public CreateCategoryInput(string name, string? description)
    {
        Name = name;
        Description = description;
    }
}
