// AUTO-GENERATED BY VELD — DO NOT EDIT

export type VeldClientConfig = {
  baseUrl?: string;
  headers?: Record<string, string>;
};

export function resolveBase(config?: VeldClientConfig | string): string {
  if (typeof config === 'string') return config;
  return config?.baseUrl ?? (typeof process !== 'undefined' ? (process.env['VELD_API_URL'] ?? '') : '');
}

export class VeldApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly body: string,
    public readonly code?: string,
  ) {
    super(`HTTP ${status}: ${body}`);
    this.name = 'VeldApiError';
  }
}

/** Type guard — narrows unknown catch value to VeldApiError. */
export function isApiError(err: unknown): err is VeldApiError {
  return err instanceof VeldApiError;
}

/**
 * Check if an error matches a specific error code.
 * Usage: if (isErrorCode(err, usersApi.errors.getUser.notFound)) { ... }
 */
export function isErrorCode<T extends string>(err: unknown, code: T): err is VeldApiError & { code: T };
export function isErrorCode(err: unknown, code: string): err is VeldApiError;
export function isErrorCode(err: unknown, code: string): err is VeldApiError {
  return err instanceof VeldApiError && err.code === code;
}

async function parseErrorResponse(res: Response): Promise<VeldApiError> {
  const text = await res.text();
  try {
    const json = JSON.parse(text);
    return new VeldApiError(res.status, json.error ?? text, json.code ?? '');
  } catch {
    return new VeldApiError(res.status, text);
  }
}

/**
 * Build a query string from an object, filtering out undefined and null values.
 * Returns '' if no valid params remain, otherwise returns '?key=value&...'.
 */
export function buildQueryString(params?: Record<string, unknown>): string {
  if (!params) return '';
  const filtered: Record<string, string> = {};
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null) {
      filtered[key] = String(value);
    }
  }
  const qs = new URLSearchParams(filtered).toString();
  return qs ? '?' + qs : '';
}

export class VeldWebSocket<TReceive, TSend = unknown> {
  private ws: WebSocket | null = null;
  private readonly listeners: Array<(msg: TReceive) => void> = [];
  private reconnectDelay = 1000;
  private closed = false;

  constructor(private readonly url: string) {}

  connect(): this {
    this.closed = false;
    this.ws = new WebSocket(this.url);
    this.ws.onmessage = (e: MessageEvent) => {
      try {
        const msg = JSON.parse(e.data as string) as TReceive;
        for (const fn of this.listeners) fn(msg);
      } catch { /* ignore malformed frames */ }
    };
    this.ws.onclose = () => {
      if (!this.closed) {
        setTimeout(() => this.connect(), this.reconnectDelay);
        this.reconnectDelay = Math.min(this.reconnectDelay * 2, 30_000);
      }
    };
    return this;
  }

  onMessage(cb: (msg: TReceive) => void): this {
    this.listeners.push(cb);
    return this;
  }

  send(msg: TSend): void {
    this.ws?.send(JSON.stringify(msg));
  }

  close(): void {
    this.closed = true;
    this.ws?.close();
  }
}
