// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase } from './_internal';
import type { PendingArtist, AdminActionMessage, PendingArtwork } from '../types';

class AdminClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** GET /api/admin/artists/pending — Get all artists waiting for approval */
  getPendingArtists(): Promise<PendingArtist[]> {
    return this.request('GET', '/api/admin/artists/pending', undefined);
  }

  /** PUT /api/admin/artists/:id/approve — Approve an artist account */
  approveArtist(id: string): Promise<AdminActionMessage> {
    return this.request('PUT', `/api/admin/artists/${id}/approve`, {});
  }

  /** PUT /api/admin/artists/:id/reject — Reject an artist account */
  rejectArtist(id: string): Promise<AdminActionMessage> {
    return this.request('PUT', `/api/admin/artists/${id}/reject`, {});
  }

  /** GET /api/admin/artworks/pending — Get all artworks waiting for approval */
  getPendingArtworks(): Promise<PendingArtwork[]> {
    return this.request('GET', '/api/admin/artworks/pending', undefined);
  }

  /** PUT /api/admin/artworks/:id/approve — Approve an artwork */
  approveArtwork(id: string): Promise<AdminActionMessage> {
    return this.request('PUT', `/api/admin/artworks/${id}/approve`, {});
  }

  /** PUT /api/admin/artworks/:id/reject — Reject an artwork */
  rejectArtwork(id: string): Promise<AdminActionMessage> {
    return this.request('PUT', `/api/admin/artworks/${id}/reject`, {});
  }
}

export { AdminClient };
export const adminApi = new AdminClient();
