// AUTO-GENERATED BY VELD — DO NOT EDIT
export type { VeldClientConfig } from './_internal';
export { VeldApiError, VeldWebSocket, isApiError, isErrorCode } from './_internal';
export * from './types';
export * from './errors';
export { UsersClient, usersApi } from './usersApi';
export { AuthClient, authApi } from './authApi';
export { ArtworksClient, artworksApi } from './artworksApi';
export { AdminClient, adminApi } from './adminApi';
export { CategoriesClient, categoriesApi } from './categoriesApi';

// Imports for VeldApiClient composition.
import { UsersClient } from './usersApi';
import { AuthClient } from './authApi';
import { ArtworksClient } from './artworksApi';
import { AdminClient } from './adminApi';
import { CategoriesClient } from './categoriesApi';


export class VeldApiClient {
  public readonly users: UsersClient;
  public readonly auth: AuthClient;
  public readonly artworks: ArtworksClient;
  public readonly admin: AdminClient;
  public readonly categories: CategoriesClient;

  constructor(config?: VeldClientConfig | string) {
    this.users = new UsersClient(config);
    this.auth = new AuthClient(config);
    this.artworks = new ArtworksClient(config);
    this.admin = new AdminClient(config);
    this.categories = new CategoriesClient(config);
  }
}

export const api = new VeldApiClient();
