// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase, buildQueryString } from './_internal';
import type { PagedArtwork, ArtworkListQuery, ArtworkDetail, PaginationQuery, CreateArtworkInput, Artwork, AdminActionMessage, ExtendAuctionTimeInput } from '../types';

class ArtworksClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** GET /api/artworks/ — Get artworks with optional filtering and pagination */
  getArtworks(query?: ArtworkListQuery): Promise<PagedArtwork> {
    return this.request('GET', '/api/artworks/' + buildQueryString(query as Record<string, unknown>), undefined);
  }

  /** GET /api/artworks/:id — Get detailed information for one artwork */
  getArtworkById(id: string): Promise<ArtworkDetail> {
    return this.request('GET', `/api/artworks/${id}`, undefined);
  }

  /** GET /api/artworks/artist/:artistId — Get paged artworks for one artist */
  getArtworksByArtist(artistId: string, query?: PaginationQuery): Promise<PagedArtwork> {
    return this.request('GET', `/api/artworks/artist/${artistId}` + buildQueryString(query as Record<string, unknown>), undefined);
  }

  /** POST /api/artworks/ — Create a new artwork (Artist role) */
  createArtwork(input: CreateArtworkInput): Promise<Artwork> {
    return this.request('POST', '/api/artworks/', input);
  }

  /** PUT /api/artworks/:id — Update an owned artwork (Artist role) */
  updateArtwork(id: string, input: CreateArtworkInput): Promise<Artwork> {
    return this.request('PUT', `/api/artworks/${id}`, input);
  }

  /** DELETE /api/artworks/:id — Delete an owned artwork (Artist role) */
  deleteArtwork(id: string): Promise<AdminActionMessage> {
    return this.request('DELETE', `/api/artworks/${id}`, {});
  }

  /** PUT /api/artworks/:id/extend — Extend auction end time (Artist role) */
  extendAuctionTime(id: string, input: ExtendAuctionTimeInput): Promise<Artwork> {
    return this.request('PUT', `/api/artworks/${id}/extend`, input);
  }
}

export { ArtworksClient };
export const artworksApi = new ArtworksClient();
