// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase } from './_internal';
import type { LoginInput, AuthToken, RegisterInput, RegisterArtistInput, User, SuccessMessage, UserRole } from '../types';

class AuthClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** POST /api/auth/login — Log in with credentials */
  login(input: LoginInput): Promise<AuthToken> {
    return this.request('POST', '/api/auth/login', input);
  }

  /** POST /api/auth/register — Register a new account */
  register(input: RegisterInput): Promise<AuthToken> {
    return this.request('POST', '/api/auth/register', input);
  }

  /** POST /api/auth/register/artist — Register a new artist account (pending approval) */
  registerArtist(input: RegisterArtistInput): Promise<AuthToken> {
    return this.request('POST', '/api/auth/register/artist', input);
  }

  /** GET /api/auth/me — Get the currently authenticated user */
  getMe(): Promise<User> {
    return this.request('GET', '/api/auth/me', undefined);
  }

  /** POST /api/auth/logout — Log out and invalidate session */
  logout(): Promise<SuccessMessage> {
    return this.request('POST', '/api/auth/logout', {});
  }
}

export { AuthClient };
export const authApi = new AuthClient();
