// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase } from './_internal';
import type { Bid } from '../types';

class bidClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** POST /api/bids/ */
  createBid(input: Bid): Promise<string> {
    return this.request('POST', '/api/bids/', input);
  }

  /** GET /api/bids/artworks/:id */
  getBids(id: string): Promise<Bid[]> {
    return this.request('GET', `/api/bids/artworks/${id}`, undefined);
  }
}

export { bidClient };
export const bidApi = new bidClient();
