// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase } from './_internal';
import type { Category, CreateCategoryInput } from '../types';

class CategoriesClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** GET /api/categories/ — List all categories */
  listCategories(): Promise<Category[]> {
    return this.request('GET', '/api/categories/', undefined);
  }

  /** POST /api/categories/ — Create category by name */
  createCategory(input: CreateCategoryInput): Promise<Category> {
    return this.request('POST', '/api/categories/', input);
  }
}

export { CategoriesClient };
export const categoriesApi = new CategoriesClient();
