// AUTO-GENERATED BY VELD — DO NOT EDIT
import { VeldApiError, VeldClientConfig, resolveBase, buildQueryString } from './_internal';
import type { User, ListQuery, CreateUserInput, UpdateUserInput, SuccessMessage, UserRole } from '../types';

class UsersClient {
  private readonly base: string;
  private readonly hdrs: Record<string, string>;

  constructor(config?: VeldClientConfig | string) {
    this.base = resolveBase(config) || "/api";
    this.hdrs = typeof config === 'object' && config !== null
      ? (config as VeldClientConfig).headers ?? {}
      : {};
  }

  private async request<T>(method: string, path: string, body?: unknown, extraHeaders?: Record<string, string>): Promise<T> {
    const res = await fetch(this.base + path, {
      method,
      headers: { 'Content-Type': 'application/json', ...this.hdrs, ...extraHeaders },
      body: body !== undefined ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) throw new VeldApiError(res.status, await res.text());
    if (res.status === 204) return undefined as T;
    return res.json() as Promise<T>;
  }

  /** GET /api/users/ — List all users with optional filters */
  listUsers(query?: ListQuery): Promise<User[]> {
    return this.request('GET', '/api/users/' + buildQueryString(query as Record<string, unknown>), undefined);
  }

  /** GET /api/users/:id — Get a single user by ID */
  getUser(id: string): Promise<User> {
    return this.request('GET', `/api/users/${id}`, undefined);
  }

  /** POST /api/users/ — Create a new user */
  createUser(input: CreateUserInput): Promise<User> {
    return this.request('POST', '/api/users/', input);
  }

  /** PUT /api/users/:id — Update an existing user */
  updateUser(id: string, input: UpdateUserInput): Promise<User> {
    return this.request('PUT', `/api/users/${id}`, input);
  }

  /** DELETE /api/users/:id — Delete a user */
  deleteUser(id: string): Promise<SuccessMessage> {
    return this.request('DELETE', `/api/users/${id}`, {});
  }
}

export { UsersClient };
export const usersApi = new UsersClient();
