// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
import { useState, useEffect, useCallback } from 'react';
import { adminApi } from '../../client/adminApi';
import type { PendingArtist, AdminActionMessage, PendingArtwork } from '../../types';

/** Get all artists waiting for approval */
export function useGetPendingArtists() {
  const [data, setData] = useState<PendingArtist[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    adminApi.getPendingArtists()
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Approve an artist account */
export function useApproveArtist() {
  const [data, setData] = useState<AdminActionMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string }) => {
    setLoading(true);
    setError(null);
    return adminApi.approveArtist(vars.id)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Reject an artist account */
export function useRejectArtist() {
  const [data, setData] = useState<AdminActionMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string }) => {
    setLoading(true);
    setError(null);
    return adminApi.rejectArtist(vars.id)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Get all artworks waiting for approval */
export function useGetPendingArtworks() {
  const [data, setData] = useState<PendingArtwork[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    adminApi.getPendingArtworks()
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Approve an artwork */
export function useApproveArtwork() {
  const [data, setData] = useState<AdminActionMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string }) => {
    setLoading(true);
    setError(null);
    return adminApi.approveArtwork(vars.id)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Reject an artwork */
export function useRejectArtwork() {
  const [data, setData] = useState<AdminActionMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string }) => {
    setLoading(true);
    setError(null);
    return adminApi.rejectArtwork(vars.id)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

export const adminHooks = {
  useGetPendingArtists,
  useApproveArtist,
  useRejectArtist,
  useGetPendingArtworks,
  useApproveArtwork,
  useRejectArtwork,
};
