// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
import { useState, useEffect, useCallback } from 'react';
import { artworksApi } from '../../client/artworksApi';
import type { PagedArtwork, ArtworkListQuery, ArtworkDetail, PaginationQuery, CreateArtworkInput, Artwork, AdminActionMessage, ExtendAuctionTimeInput } from '../../types';

/** Get artworks with optional filtering and pagination */
export function useGetArtworks(query?: ArtworkListQuery) {
  const [data, setData] = useState<PagedArtwork | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    artworksApi.getArtworks(query)
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(query)]);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Get detailed information for one artwork */
export function useGetArtworkById(id: string) {
  const [data, setData] = useState<ArtworkDetail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    artworksApi.getArtworkById(id)
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Get paged artworks for one artist */
export function useGetArtworksByArtist(artistId: string, query?: PaginationQuery) {
  const [data, setData] = useState<PagedArtwork | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    artworksApi.getArtworksByArtist(artistId, query)
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [artistId, JSON.stringify(query)]);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Create a new artwork (Artist role) */
export function useCreateArtwork() {
  const [data, setData] = useState<Artwork | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { input: CreateArtworkInput }) => {
    setLoading(true);
    setError(null);
    return artworksApi.createArtwork(vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Update an owned artwork (Artist role) */
export function useUpdateArtwork() {
  const [data, setData] = useState<Artwork | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string; input: CreateArtworkInput }) => {
    setLoading(true);
    setError(null);
    return artworksApi.updateArtwork(vars.id, vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Delete an owned artwork (Artist role) */
export function useDeleteArtwork() {
  const [data, setData] = useState<AdminActionMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string }) => {
    setLoading(true);
    setError(null);
    return artworksApi.deleteArtwork(vars.id)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Extend auction end time (Artist role) */
export function useExtendAuctionTime() {
  const [data, setData] = useState<Artwork | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { id: string; input: ExtendAuctionTimeInput }) => {
    setLoading(true);
    setError(null);
    return artworksApi.extendAuctionTime(vars.id, vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

export const artworksHooks = {
  useGetArtworks,
  useGetArtworkById,
  useGetArtworksByArtist,
  useCreateArtwork,
  useUpdateArtwork,
  useDeleteArtwork,
  useExtendAuctionTime,
};
