// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
import { useState, useEffect, useCallback } from 'react';
import { authApi } from '../../client/authApi';
import type { LoginInput, AuthToken, RegisterInput, User, SuccessMessage, UserRole } from '../../types';

/** Log in with credentials */
export function useLogin() {
  const [data, setData] = useState<AuthToken | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { input: LoginInput }) => {
    setLoading(true);
    setError(null);
    return authApi.login(vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Register a new account */
export function useRegister() {
  const [data, setData] = useState<AuthToken | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { input: RegisterInput }) => {
    setLoading(true);
    setError(null);
    return authApi.register(vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/** Get the currently authenticated user */
export function useGetMe() {
  const [data, setData] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    authApi.getMe()
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Log out and invalidate session */
export function useLogout() {
  const [data, setData] = useState<SuccessMessage | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback(() => {
    setLoading(true);
    setError(null);
    return authApi.logout()
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

export const authHooks = {
  useLogin,
  useRegister,
  useGetMe,
  useLogout,
};
