// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
import { useState, useEffect, useCallback } from 'react';
import { bidApi } from '../../client/bidApi';
import type { Bid } from '../../types';

/**  */
export function useCreateBid() {
  const [data, setData] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { input: Bid }) => {
    setLoading(true);
    setError(null);
    return bidApi.createBid(vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

/**  */
export function useGetBids(id: string) {
  const [data, setData] = useState<Bid[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    bidApi.getBids(id)
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

export const bidHooks = {
  useCreateBid,
  useGetBids,
};
