// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
import { useState, useEffect, useCallback } from 'react';
import { categoriesApi } from '../../client/categoriesApi';
import type { Category, CreateCategoryInput } from '../../types';

/** List all categories */
export function useListCategories() {
  const [data, setData] = useState<Category[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetch = useCallback(() => {
    setLoading(true);
    setError(null);
    categoriesApi.listCategories()
      .then((result) => { setData(result); })
      .catch((err) => { setError(err); })
      .finally(() => { setLoading(false); });
  }, []);

  useEffect(() => { fetch(); }, [fetch]);

  return { data, loading, error, refetch: fetch };
}

/** Create category by name */
export function useCreateCategory() {
  const [data, setData] = useState<Category | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);

  const mutate = useCallback((vars: { input: CreateCategoryInput }) => {
    setLoading(true);
    setError(null);
    return categoriesApi.createCategory(vars.input)
      .then((result) => { setData(result); return result; })
      .catch((err) => { setError(err); throw err; })
      .finally(() => { setLoading(false); });
  }, []);

  return { mutate, data, loading, error };
}

export const categoriesHooks = {
  useListCategories,
  useCreateCategory,
};
