// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
export { adminHooks } from './adminHooks';
export { artworksHooks } from './artworksHooks';
export { authHooks } from './authHooks';
export { usersHooks } from './usersHooks';
