// AUTO-GENERATED BY VELD — DO NOT EDIT
// Zero-dependency hooks — no TanStack Query required.
export { usersHooks } from './usersHooks';
export { authHooks } from './authHooks';
export { artworksHooks } from './artworksHooks';
export { adminHooks } from './adminHooks';
export { categoriesHooks } from './categoriesHooks';
