// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Text.Json.Serialization;

namespace VeldGenerated.Models;

public class Bid
{
    [JsonPropertyName("id")]
    public string Id { get; set; }

    [JsonPropertyName("issuerId")]
    public string IssuerId { get; set; }

    [JsonPropertyName("artId")]
    public string ArtId { get; set; }

    [JsonPropertyName("amount")]
    public decimal Amount { get; set; }

    [JsonPropertyName("highestBidder")]
    public bool HighestBidder { get; set; }

    [JsonPropertyName("placed")]
    public DateTime Placed { get; set; }

    public Bid() { }

    public Bid(string id, string issuerId, string artId, decimal amount, bool highestBidder, DateTime placed)
    {
        Id = id;
        IssuerId = issuerId;
        ArtId = artId;
        Amount = amount;
        HighestBidder = highestBidder;
        Placed = placed;
    }
}
