// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;

namespace VeldGenerated.Services;

/// <summary>Admin review and approval endpoints</summary>
public interface IAdminService
{
    /// <summary>Get all artists waiting for approval</summary>
    Task<List<PendingArtist>> GetPendingArtists();

    /// <summary>Approve an artist account</summary>
    Task<AdminActionMessage> ApproveArtist(string Id);

    /// <summary>Reject an artist account</summary>
    Task<AdminActionMessage> RejectArtist(string Id);

    /// <summary>Get all artworks waiting for approval</summary>
    Task<List<PendingArtwork>> GetPendingArtworks();

    /// <summary>Approve an artwork</summary>
    Task<AdminActionMessage> ApproveArtwork(string Id);

    /// <summary>Reject an artwork</summary>
    Task<AdminActionMessage> RejectArtwork(string Id);

}
