// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;

namespace VeldGenerated.Services;

/// <summary>Artwork browsing and management</summary>
public interface IArtworksService
{
    /// <summary>Get artworks with optional filtering and pagination</summary>
    Task<PagedArtwork> GetArtworks(Dictionary<string, string> query);

    /// <summary>Get detailed information for one artwork</summary>
    Task<ArtworkDetail> GetArtworkById(string Id);

    /// <summary>Get paged artworks for one artist</summary>
    Task<PagedArtwork> GetArtworksByArtist(string ArtistId, Dictionary<string, string> query);

    /// <summary>Create a new artwork (Artist role)</summary>
    Task<Artwork> CreateArtwork(CreateArtworkInput input);

    /// <summary>Update an owned artwork (Artist role)</summary>
    Task<Artwork> UpdateArtwork(string Id, CreateArtworkInput input);

    /// <summary>Delete an owned artwork (Artist role)</summary>
    Task<AdminActionMessage> DeleteArtwork(string Id);

    /// <summary>Extend auction end time (Artist role)</summary>
    Task<Artwork> ExtendAuctionTime(string Id, ExtendAuctionTimeInput input);

}
