// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;

namespace VeldGenerated.Services;

/// <summary>Authentication and session management</summary>
public interface IAuthService
{
    /// <summary>Log in with credentials</summary>
    Task<AuthToken> Login(LoginInput input);

    /// <summary>Register a new account</summary>
    Task<AuthToken> Register(RegisterInput input);

    /// <summary>Register a new artist account (pending approval)</summary>
    Task<AuthToken> RegisterArtist(RegisterArtistInput input);

    /// <summary>Get the currently authenticated user</summary>
    Task<User> GetMe();

    /// <summary>Log out and invalidate session</summary>
    Task<SuccessMessage> Logout();

}
