// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;

namespace VeldGenerated.Services;

public interface IBidService
{
    Task<string> CreateBid(Bid input);

    Task<List<Bid>> GetBids(string Id);

}
