// AUTO-GENERATED BY VELD — DO NOT EDIT
using System.Collections.Generic;
using VeldGenerated.Models;
using VeldGenerated.Errors;

namespace VeldGenerated.Services;

/// <summary>Category management</summary>
public interface ICategoriesService
{
    /// <summary>List all categories</summary>
    Task<List<Category>> ListCategories();

    /// <summary>Create category by name</summary>
    Task<Category> CreateCategory(CreateCategoryInput input);

}
