// AUTO-GENERATED BY VELD — DO NOT EDIT
/** A UUID string (e.g. "550e8400-e29b-41d4-a716-446655440000"). */
export type UUID = string & { readonly __brand: 'UUID' };
/** A decimal value represented as a string for precision (e.g. "12345.6789"). */
export type Decimal = string & { readonly __brand: 'Decimal' };
/** An ISO 8601 datetime string (e.g. "2024-01-15T09:30:00Z"). */
export type ISODateTime = string & { readonly __brand: 'ISODateTime' };
