// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UUID, ISODateTime } from './_scalars';
export type { AdminActionMessage } from './artworks';

/** Artist account waiting for admin approval */
export class PendingArtist {
  id!: UUID;
  username!: string;
  email!: string;
  createdAt!: ISODateTime;

  constructor(data?: Partial<PendingArtist>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getUsername(): string { return this.username; }
  setUsername(value: string): void { this.username = value; }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getCreatedAt(): ISODateTime { return this.createdAt; }
  setCreatedAt(value: ISODateTime): void { this.createdAt = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): PendingArtist { return new PendingArtist(data as any); }
}

/** Artwork waiting for admin approval */
export class PendingArtwork {
  id!: UUID;
  title!: string;
  description!: string;
  initialPrice!: number;
  artistName!: string;
  createdAt!: ISODateTime;

  constructor(data?: Partial<PendingArtwork>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getTitle(): string { return this.title; }
  setTitle(value: string): void { this.title = value; }

  getDescription(): string { return this.description; }
  setDescription(value: string): void { this.description = value; }

  getInitialPrice(): number { return this.initialPrice; }
  setInitialPrice(value: number): void { this.initialPrice = value; }

  getArtistName(): string { return this.artistName; }
  setArtistName(value: string): void { this.artistName = value; }

  getCreatedAt(): ISODateTime { return this.createdAt; }
  setCreatedAt(value: ISODateTime): void { this.createdAt = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): PendingArtwork { return new PendingArtwork(data as any); }
}

