// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UUID, ISODateTime } from './_scalars';
/** Lightweight artwork card */
export class Artwork {
  id!: UUID;
  title!: string;
  artistName!: string;
  categoryName!: string;
  initialPrice!: number;
  currentBid!: number;
  auctionEndTime!: ISODateTime;
  status!: string;
  imageUrl!: string;

  constructor(data?: Partial<Artwork>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getTitle(): string { return this.title; }
  setTitle(value: string): void { this.title = value; }

  getArtistName(): string { return this.artistName; }
  setArtistName(value: string): void { this.artistName = value; }

  getCategoryName(): string { return this.categoryName; }
  setCategoryName(value: string): void { this.categoryName = value; }

  getInitialPrice(): number { return this.initialPrice; }
  setInitialPrice(value: number): void { this.initialPrice = value; }

  getCurrentBid(): number { return this.currentBid; }
  setCurrentBid(value: number): void { this.currentBid = value; }

  getAuctionEndTime(): ISODateTime { return this.auctionEndTime; }
  setAuctionEndTime(value: ISODateTime): void { this.auctionEndTime = value; }

  getStatus(): string { return this.status; }
  setStatus(value: string): void { this.status = value; }

  getImageUrl(): string { return this.imageUrl; }
  setImageUrl(value: string): void { this.imageUrl = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): Artwork { return new Artwork(data as any); }
}

/** Detailed artwork payload */
export class ArtworkDetail {
  id!: UUID;
  title!: string;
  description!: string;
  artistName!: string;
  artistId!: UUID;
  initialPrice!: number;
  buyNowPrice?: number;
  currentBid!: number;
  auctionStartTime!: ISODateTime;
  auctionEndTime!: ISODateTime;
  status!: string;
  categoryName!: string;
  tags!: string[];
  totalBids!: number;
  imageUrl!: string;
  createdAt!: ISODateTime;

  constructor(data?: Partial<ArtworkDetail>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getTitle(): string { return this.title; }
  setTitle(value: string): void { this.title = value; }

  getDescription(): string { return this.description; }
  setDescription(value: string): void { this.description = value; }

  getArtistName(): string { return this.artistName; }
  setArtistName(value: string): void { this.artistName = value; }

  getArtistId(): UUID { return this.artistId; }
  setArtistId(value: UUID): void { this.artistId = value; }

  getInitialPrice(): number { return this.initialPrice; }
  setInitialPrice(value: number): void { this.initialPrice = value; }

  getBuyNowPrice(): number | undefined { return this.buyNowPrice; }
  setBuyNowPrice(value: number | undefined): void { this.buyNowPrice = value; }

  getCurrentBid(): number { return this.currentBid; }
  setCurrentBid(value: number): void { this.currentBid = value; }

  getAuctionStartTime(): ISODateTime { return this.auctionStartTime; }
  setAuctionStartTime(value: ISODateTime): void { this.auctionStartTime = value; }

  getAuctionEndTime(): ISODateTime { return this.auctionEndTime; }
  setAuctionEndTime(value: ISODateTime): void { this.auctionEndTime = value; }

  getStatus(): string { return this.status; }
  setStatus(value: string): void { this.status = value; }

  getCategoryName(): string { return this.categoryName; }
  setCategoryName(value: string): void { this.categoryName = value; }

  getTags(): string[] { return this.tags; }
  setTags(value: string[]): void { this.tags = value; }

  getTotalBids(): number { return this.totalBids; }
  setTotalBids(value: number): void { this.totalBids = value; }

  getImageUrl(): string { return this.imageUrl; }
  setImageUrl(value: string): void { this.imageUrl = value; }

  getCreatedAt(): ISODateTime { return this.createdAt; }
  setCreatedAt(value: ISODateTime): void { this.createdAt = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ArtworkDetail { return new ArtworkDetail(data as any); }
}

/** Payload used for create and update artwork */
export class CreateArtworkInput {
  title!: string;
  description!: string;
  initialPrice!: number;
  buyNowPrice?: number;
  auctionStartTime!: ISODateTime;
  auctionEndTime!: ISODateTime;
  categoryName!: string;
  tags!: string[];
  imageUrl!: string;

  constructor(data?: Partial<CreateArtworkInput>) {
    if (data) Object.assign(this, data);
  }

  getTitle(): string { return this.title; }
  setTitle(value: string): void { this.title = value; }

  getDescription(): string { return this.description; }
  setDescription(value: string): void { this.description = value; }

  getInitialPrice(): number { return this.initialPrice; }
  setInitialPrice(value: number): void { this.initialPrice = value; }

  getBuyNowPrice(): number | undefined { return this.buyNowPrice; }
  setBuyNowPrice(value: number | undefined): void { this.buyNowPrice = value; }

  getAuctionStartTime(): ISODateTime { return this.auctionStartTime; }
  setAuctionStartTime(value: ISODateTime): void { this.auctionStartTime = value; }

  getAuctionEndTime(): ISODateTime { return this.auctionEndTime; }
  setAuctionEndTime(value: ISODateTime): void { this.auctionEndTime = value; }

  getCategoryName(): string { return this.categoryName; }
  setCategoryName(value: string): void { this.categoryName = value; }

  getTags(): string[] { return this.tags; }
  setTags(value: string[]): void { this.tags = value; }

  getImageUrl(): string { return this.imageUrl; }
  setImageUrl(value: string): void { this.imageUrl = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): CreateArtworkInput { return new CreateArtworkInput(data as any); }
}

/** Payload used to extend auction end time */
export class ExtendAuctionTimeInput {
  newEndTime!: ISODateTime;

  constructor(data?: Partial<ExtendAuctionTimeInput>) {
    if (data) Object.assign(this, data);
  }

  getNewEndTime(): ISODateTime { return this.newEndTime; }
  setNewEndTime(value: ISODateTime): void { this.newEndTime = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ExtendAuctionTimeInput { return new ExtendAuctionTimeInput(data as any); }
}

/** Filters for the public artworks list */
export class ArtworkListQuery {
  pageNumber?: number;
  pageSize?: number;
  artistName?: string;
  categoryName?: string;
  tagName?: string;
  status?: string;

  constructor(data?: Partial<ArtworkListQuery>) {
    if (data) Object.assign(this, data);
  }

  getPageNumber(): number | undefined { return this.pageNumber; }
  setPageNumber(value: number | undefined): void { this.pageNumber = value; }

  getPageSize(): number | undefined { return this.pageSize; }
  setPageSize(value: number | undefined): void { this.pageSize = value; }

  getArtistName(): string | undefined { return this.artistName; }
  setArtistName(value: string | undefined): void { this.artistName = value; }

  getCategoryName(): string | undefined { return this.categoryName; }
  setCategoryName(value: string | undefined): void { this.categoryName = value; }

  getTagName(): string | undefined { return this.tagName; }
  setTagName(value: string | undefined): void { this.tagName = value; }

  getStatus(): string | undefined { return this.status; }
  setStatus(value: string | undefined): void { this.status = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ArtworkListQuery { return new ArtworkListQuery(data as any); }
}

/** Basic pagination query */
export class PaginationQuery {
  pageNumber?: number;
  pageSize?: number;

  constructor(data?: Partial<PaginationQuery>) {
    if (data) Object.assign(this, data);
  }

  getPageNumber(): number | undefined { return this.pageNumber; }
  setPageNumber(value: number | undefined): void { this.pageNumber = value; }

  getPageSize(): number | undefined { return this.pageSize; }
  setPageSize(value: number | undefined): void { this.pageSize = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): PaginationQuery { return new PaginationQuery(data as any); }
}

/** Paged list response for artworks */
export class PagedArtwork {
  items!: Artwork[];
  totalCount!: number;
  pageNumber!: number;
  pageSize!: number;
  totalPages!: number;
  hasNextPage!: boolean;
  hasPreviousPage!: boolean;

  constructor(data?: Partial<PagedArtwork>) {
    if (data) Object.assign(this, data);
  }

  getItems(): Artwork[] { return this.items; }
  setItems(value: Artwork[]): void { this.items = value; }

  getTotalCount(): number { return this.totalCount; }
  setTotalCount(value: number): void { this.totalCount = value; }

  getPageNumber(): number { return this.pageNumber; }
  setPageNumber(value: number): void { this.pageNumber = value; }

  getPageSize(): number { return this.pageSize; }
  setPageSize(value: number): void { this.pageSize = value; }

  getTotalPages(): number { return this.totalPages; }
  setTotalPages(value: number): void { this.totalPages = value; }

  getHasNextPage(): boolean { return this.hasNextPage; }
  setHasNextPage(value: boolean): void { this.hasNextPage = value; }

  getHasPreviousPage(): boolean { return this.hasPreviousPage; }
  setHasPreviousPage(value: boolean): void { this.hasPreviousPage = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): PagedArtwork { return new PagedArtwork(data as any); }
}

/** Message returned after approve/reject actions */
export class AdminActionMessage {
  message!: string;

  constructor(data?: Partial<AdminActionMessage>) {
    if (data) Object.assign(this, data);
  }

  getMessage(): string { return this.message; }
  setMessage(value: string): void { this.message = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): AdminActionMessage { return new AdminActionMessage(data as any); }
}

