// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { User } from './users';
export type { SuccessMessage, User, UserRole } from './users';

/** Credentials for user login */
export class LoginInput {
  email!: string;
  password!: string;

  constructor(data?: Partial<LoginInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): LoginInput { return new LoginInput(data as any); }
}

/** Data for new account registration */
export class RegisterInput {
  email!: string;
  name!: string;
  password!: string;
  role?: string;

  constructor(data?: Partial<RegisterInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  getRole(): string | undefined { return this.role; }
  setRole(value: string | undefined): void { this.role = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): RegisterInput { return new RegisterInput(data as any); }
}

/** Data for artist account registration */
export class RegisterArtistInput {
  email!: string;
  name!: string;
  password!: string;

  constructor(data?: Partial<RegisterArtistInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): RegisterArtistInput { return new RegisterArtistInput(data as any); }
}

/** Token returned after successful authentication */
export class AuthToken {
  token!: string;
  user!: User;

  constructor(data?: Partial<AuthToken>) {
    if (data) Object.assign(this, data);
  }

  getToken(): string { return this.token; }
  setToken(value: string): void { this.token = value; }

  getUser(): User { return this.user; }
  setUser(value: User): void { this.user = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): AuthToken { return new AuthToken(data as any); }
}

