// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UUID, ISODateTime } from './_scalars';
export type UserRole = "admin" | "user" | "guest";

/** A platform user */
export class User {
  id!: UUID;
  email!: string;
  name!: string;
  bio?: string;
  role!: UserRole;
  verified!: boolean = false;
  createdAt!: ISODateTime;

  constructor(data?: Partial<User>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getBio(): string | undefined { return this.bio; }
  setBio(value: string | undefined): void { this.bio = value; }

  getRole(): UserRole { return this.role; }
  setRole(value: UserRole): void { this.role = value; }

  getVerified(): boolean { return this.verified; }
  setVerified(value: boolean): void { this.verified = value; }

  getCreatedAt(): ISODateTime { return this.createdAt; }
  setCreatedAt(value: ISODateTime): void { this.createdAt = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): User { return new User(data as any); }
}

/** Credentials for user login */
export class LoginInput {
  email!: string;
  password!: string;

  constructor(data?: Partial<LoginInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): LoginInput { return new LoginInput(data as any); }
}

/** Data for new account registration */
export class RegisterInput {
  email!: string;
  name!: string;
  password!: string;

  constructor(data?: Partial<RegisterInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): RegisterInput { return new RegisterInput(data as any); }
}

/** Token returned after successful authentication */
export class AuthToken {
  token!: string;
  user!: User;

  constructor(data?: Partial<AuthToken>) {
    if (data) Object.assign(this, data);
  }

  getToken(): string { return this.token; }
  setToken(value: string): void { this.token = value; }

  getUser(): User { return this.user; }
  setUser(value: User): void { this.user = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): AuthToken { return new AuthToken(data as any); }
}

/** Generic success response */
export class SuccessMessage {
  success!: boolean;
  message?: string;

  constructor(data?: Partial<SuccessMessage>) {
    if (data) Object.assign(this, data);
  }

  getSuccess(): boolean { return this.success; }
  setSuccess(value: boolean): void { this.success = value; }

  getMessage(): string | undefined { return this.message; }
  setMessage(value: string | undefined): void { this.message = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): SuccessMessage { return new SuccessMessage(data as any); }
}

