// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { Decimal, ISODateTime } from './_scalars';
export class Bid {
  id!: string;
  issuerId!: string;
  artId!: string;
  amount!: Decimal;
  highestBidder!: boolean;
  placed!: ISODateTime;

  constructor(data?: Partial<Bid>) {
    if (data) Object.assign(this, data);
  }

  getId(): string { return this.id; }
  setId(value: string): void { this.id = value; }

  getIssuerId(): string { return this.issuerId; }
  setIssuerId(value: string): void { this.issuerId = value; }

  getArtId(): string { return this.artId; }
  setArtId(value: string): void { this.artId = value; }

  getAmount(): Decimal { return this.amount; }
  setAmount(value: Decimal): void { this.amount = value; }

  getHighestBidder(): boolean { return this.highestBidder; }
  setHighestBidder(value: boolean): void { this.highestBidder = value; }

  getPlaced(): ISODateTime { return this.placed; }
  setPlaced(value: ISODateTime): void { this.placed = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): Bid { return new Bid(data as any); }
}

