// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UUID } from './_scalars';
/** Artwork category */
export class Category {
  id!: UUID;
  name!: string;
  description!: string;

  constructor(data?: Partial<Category>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getDescription(): string { return this.description; }
  setDescription(value: string): void { this.description = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): Category { return new Category(data as any); }
}

/** Payload to create category */
export class CreateCategoryInput {
  name!: string;
  description?: string;

  constructor(data?: Partial<CreateCategoryInput>) {
    if (data) Object.assign(this, data);
  }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getDescription(): string | undefined { return this.description; }
  setDescription(value: string | undefined): void { this.description = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): CreateCategoryInput { return new CreateCategoryInput(data as any); }
}

