// AUTO-GENERATED BY VELD — DO NOT EDIT
/** Error response payload */
export class ErrorMessage {
  error!: string;

  constructor(data?: Partial<ErrorMessage>) {
    if (data) Object.assign(this, data);
  }

  getError(): string { return this.error; }
  setError(value: string): void { this.error = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ErrorMessage { return new ErrorMessage(data as any); }
}

