// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UUID, ISODateTime } from './_scalars';
export type UserRole = "admin" | "user" | "artist" | "guest";

/** A platform user */
export class User {
  id!: UUID;
  email!: string;
  name!: string;
  bio?: string;
  role!: UserRole;
  verified!: boolean = false;
  createdAt!: ISODateTime;

  constructor(data?: Partial<User>) {
    if (data) Object.assign(this, data);
  }

  getId(): UUID { return this.id; }
  setId(value: UUID): void { this.id = value; }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getBio(): string | undefined { return this.bio; }
  setBio(value: string | undefined): void { this.bio = value; }

  getRole(): UserRole { return this.role; }
  setRole(value: UserRole): void { this.role = value; }

  getVerified(): boolean { return this.verified; }
  setVerified(value: boolean): void { this.verified = value; }

  getCreatedAt(): ISODateTime { return this.createdAt; }
  setCreatedAt(value: ISODateTime): void { this.createdAt = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): User { return new User(data as any); }
}

/** Data required to create a new user */
export class CreateUserInput {
  email!: string;
  name!: string;
  password!: string;

  constructor(data?: Partial<CreateUserInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): CreateUserInput { return new CreateUserInput(data as any); }
}

/** Fields that can be updated on a user */
export class UpdateUserInput {
  name?: string;
  bio?: string;
  role?: UserRole;

  constructor(data?: Partial<UpdateUserInput>) {
    if (data) Object.assign(this, data);
  }

  getName(): string | undefined { return this.name; }
  setName(value: string | undefined): void { this.name = value; }

  getBio(): string | undefined { return this.bio; }
  setBio(value: string | undefined): void { this.bio = value; }

  getRole(): UserRole | undefined { return this.role; }
  setRole(value: UserRole | undefined): void { this.role = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): UpdateUserInput { return new UpdateUserInput(data as any); }
}

/** Generic success response */
export class SuccessMessage {
  success!: boolean;
  message?: string;

  constructor(data?: Partial<SuccessMessage>) {
    if (data) Object.assign(this, data);
  }

  getSuccess(): boolean { return this.success; }
  setSuccess(value: boolean): void { this.success = value; }

  getMessage(): string | undefined { return this.message; }
  setMessage(value: string | undefined): void { this.message = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): SuccessMessage { return new SuccessMessage(data as any); }
}

/** Common query parameters for list endpoints */
export class ListQuery {
  search?: string;
  limit?: number;
  offset?: number;

  constructor(data?: Partial<ListQuery>) {
    if (data) Object.assign(this, data);
  }

  getSearch(): string | undefined { return this.search; }
  setSearch(value: string | undefined): void { this.search = value; }

  getLimit(): number | undefined { return this.limit; }
  setLimit(value: number | undefined): void { this.limit = value; }

  getOffset(): number | undefined { return this.offset; }
  setOffset(value: number | undefined): void { this.offset = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ListQuery { return new ListQuery(data as any); }
}

