// AUTO-GENERATED BY VELD — DO NOT EDIT
import type { UserRole } from './auth';
export type { SuccessMessage, User, UserRole } from './auth';

/** Data required to create a new user */
export class CreateUserInput {
  email!: string;
  name!: string;
  password!: string;

  constructor(data?: Partial<CreateUserInput>) {
    if (data) Object.assign(this, data);
  }

  getEmail(): string { return this.email; }
  setEmail(value: string): void { this.email = value; }

  getName(): string { return this.name; }
  setName(value: string): void { this.name = value; }

  getPassword(): string { return this.password; }
  setPassword(value: string): void { this.password = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): CreateUserInput { return new CreateUserInput(data as any); }
}

/** Fields that can be updated on a user */
export class UpdateUserInput {
  name?: string;
  bio?: string;
  role?: UserRole;

  constructor(data?: Partial<UpdateUserInput>) {
    if (data) Object.assign(this, data);
  }

  getName(): string | undefined { return this.name; }
  setName(value: string | undefined): void { this.name = value; }

  getBio(): string | undefined { return this.bio; }
  setBio(value: string | undefined): void { this.bio = value; }

  getRole(): UserRole | undefined { return this.role; }
  setRole(value: UserRole | undefined): void { this.role = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): UpdateUserInput { return new UpdateUserInput(data as any); }
}

/** Common query parameters for list endpoints */
export class ListQuery {
  search?: string;
  limit?: number;
  offset?: number;

  constructor(data?: Partial<ListQuery>) {
    if (data) Object.assign(this, data);
  }

  getSearch(): string | undefined { return this.search; }
  setSearch(value: string | undefined): void { this.search = value; }

  getLimit(): number | undefined { return this.limit; }
  setLimit(value: number | undefined): void { this.limit = value; }

  getOffset(): number | undefined { return this.offset; }
  setOffset(value: number | undefined): void { this.offset = value; }

  toJSON(): Record<string, unknown> { return { ...this }; }
  static fromJSON(data: Record<string, unknown>): ListQuery { return new ListQuery(data as any); }
}

