name: Deploy Backend (Dev)

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    name: Deploy DEV
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth DEV to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Set project
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Docker auth
        run: gcloud auth configure-docker ${{ secrets.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: |
          docker build \
            -f backend/src/API/Dockerfile \
            -t ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend/backend:${{ github.sha }} \
            backend/src

      - name: Push image
        run: |
          docker push ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend/backend:${{ github.sha }}

      - name: Deploy DEV
        run: |
          gcloud run deploy joint-backend-dev \
            --image ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend/backend:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars ASPNETCORE_URLS=http://0.0.0.0:8080 \
            --quiet